### ISSUE TITLE
Unable to invoke the batchGetItem

### ISSUE THREAD

**Issue by ZaidMomin1** [Shadowblazen/dynamodb-wrapper#3]
I have the below code:

`
getParams = {
    RequestItems: {
        "masterTable": {
            Keys: [{
                "FulfillerID": {
                    S: "88"
                }
            }]
        }
    }
};
dynamoDBWrapper.batchGetItem(getParams)
    .then(function(response) {
        console.log("Response");
        console.log(response.RequestItems);
    })
    .catch(function(error) {
        console.log("Error");
        console.log(error);
    });
`

Actual Error:
dynamoDBWrapper.batchGetItem(getParams,{})
                                ^
TypeError: dynamoDBWrapper.batchGetItem is not a function

Note:
1. I see on github there is the method for batchGetItem(), but when I install the library on my machine (v.1.3.0) i see that batchGetItem() method does not exists.

**Comment by Shadowblazen** [comment]
Sorry for the late reply,

~~Yes, that method is not released to npm yet. A few months ago I pre-emptively updated the documentation thinking I was going to be releasing a new version soon and then that never happened.~~

~~I've removed it from the documentation to avoid confusion for now.~~

**EDIT:** v1.4.0 was released to npm, which contains the `batchGetItem()` API method.
